name: flutter_readable
description: extensions and helpers for dart to save time , make the code more readable and smaller
version: 0.0.5
homepage: https://github.com/FlutterQueen/readable

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  readable: ^0.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.7.2
