name: queen
description: opinionated framework built in top of flutter to deliver faster apps , readable ,simpler code
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_readable: ^0.0.5
  nations_assets: ^0.0.4
  queen_validators: ^1.0.0
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.3
  nations:
    path: ../nations
  locators:
    path: ../locators
  queen_themes:
    path: ../queen_themes
dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.8.2
